-- MONTHLY PORTFOLIO / 新ページ専用 Supabase 設定
-- すでに今回の会話で Success. No rows returned まで完了している場合、再実行は不要です。

create table if not exists public.monthly_portfolio_works (
  id bigint generated by default as identity primary key,
  title text,
  note text,
  image_url text,
  category text,
  work_month smallint check (work_month between 1 and 12),
  created_at timestamptz default now()
);

alter table public.monthly_portfolio_works
  add column if not exists tags text[] not null default '{}',
  add column if not exists published boolean not null default true,
  add column if not exists storage_path text,
  add column if not exists sort_order integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();

alter table public.monthly_portfolio_works enable row level security;

create or replace function public.is_portfolio_admin()
returns boolean
language sql
stable
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'portfolio_admin')::boolean,
    false
  );
$$;

revoke all on function public.is_portfolio_admin() from public;
grant execute on function public.is_portfolio_admin() to anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on table public.monthly_portfolio_works to anon, authenticated;
grant insert, update, delete on table public.monthly_portfolio_works to authenticated;
grant usage, select on sequence public.monthly_portfolio_works_id_seq to authenticated;

drop policy if exists "monthly portfolio public can read published" on public.monthly_portfolio_works;
create policy "monthly portfolio public can read published"
on public.monthly_portfolio_works for select
to public
using (published = true);

drop policy if exists "monthly portfolio admin can read all" on public.monthly_portfolio_works;
create policy "monthly portfolio admin can read all"
on public.monthly_portfolio_works for select
to authenticated
using (public.is_portfolio_admin());

drop policy if exists "monthly portfolio admin can insert" on public.monthly_portfolio_works;
create policy "monthly portfolio admin can insert"
on public.monthly_portfolio_works for insert
to authenticated
with check (public.is_portfolio_admin());

drop policy if exists "monthly portfolio admin can update" on public.monthly_portfolio_works;
create policy "monthly portfolio admin can update"
on public.monthly_portfolio_works for update
to authenticated
using (public.is_portfolio_admin())
with check (public.is_portfolio_admin());

drop policy if exists "monthly portfolio admin can delete" on public.monthly_portfolio_works;
create policy "monthly portfolio admin can delete"
on public.monthly_portfolio_works for delete
to authenticated
using (public.is_portfolio_admin());

insert into storage.buckets (id, name, public)
values ('monthly-portfolio', 'monthly-portfolio', true)
on conflict (id) do update set public = true;

drop policy if exists "monthly portfolio storage insert" on storage.objects;
create policy "monthly portfolio storage insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'monthly-portfolio' and public.is_portfolio_admin());

drop policy if exists "monthly portfolio storage update" on storage.objects;
create policy "monthly portfolio storage update"
on storage.objects for update
to authenticated
using (bucket_id = 'monthly-portfolio' and public.is_portfolio_admin())
with check (bucket_id = 'monthly-portfolio' and public.is_portfolio_admin());

drop policy if exists "monthly portfolio storage delete" on storage.objects;
create policy "monthly portfolio storage delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'monthly-portfolio' and public.is_portfolio_admin());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'monthly_portfolio_works'
  ) then
    alter publication supabase_realtime add table public.monthly_portfolio_works;
  end if;
end $$;
